name: dio_http_cache
description: http cache lib for Flutter dio like RxCache.It use sqflite as disk cache,and google/quiver-dart/LRU strategy as memory cache.
version: 0.4.0
homepage: https://github.com/hurshi/dio-http-cache

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  crypto: ^3.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  path: ^1.8.1
  quiver: ^3.1.0
  sqflite: ^2.0.3+1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter

flutter:
  module:
    androidX: true
